package com.example.survey.dto;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Data;
import java.util.List;

@Data
public class SurveySubmissionRequest {

    @Size(max = 200)
    private String phoneNumber;
    @Size(max = 100)
    private String ageGroup;
    @Size(max = 100)
    private String diningFrequency;

    /**
     * A per-page-load UUID generated by the frontend on every onMounted.
     * When present, the backend uses it as the participant ID so that each
     * time the survey is opened it is treated as an independent new session,
     * regardless of any existing participant cookie.
     */
    @Size(max = 36)
    private String sessionId;

    @NotNull
    @Size(min = 1, max = 1000, message = "Submission must contain between 1 and 1000 answers")
    @Valid
    private List<@NotNull CategorySubmissionDTO> answers;
}