package com.example.survey.dto;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Data;
import java.util.List;

@Data
public class SurveySubmissionRequest {

    private String phoneNumber;
    private String ageGroup;
    private String diningFrequency;

    /**
     * A per-page-load UUID generated by the frontend on every onMounted.
     * When present, the backend uses it as the participant ID so that each
     * time the survey is opened it is treated as an independent new session,
     * regardless of any existing participant cookie.
     */
    private String sessionId;

    @NotNull
    @Size(min = 1, message = "Submission must contain at least one answer")
    @Valid
    private List<CategorySubmissionDTO> answers;
}