spring.application.name=Survey

#Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.open-in-view=false

spring.sql.init.mode=${SPRING_SQL_INIT_MODE:never}
spring.jpa.defer-datasource-initialization=true

admin.username=${ADMIN_USER}
admin.password-hash=${ADMIN_PASSWORD_HASH}
jwt.secret=${JWT_SECRET}

server.port=${PORT:8080}