spring.application.name=Survey

#Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

admin.username=${ADMIN_USER}
admin.password=${ADMIN_PASS}
jwt.secret=${JWT_SECRET}

spring.security.user.name=${admin.username}
spring.security.user.password=${admin.password}

server.port=${PORT:8080}